<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 1,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            1 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 2,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            2 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Email',
                'edit' => 1,
                'field' => 'email',
                'id' => 3,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            3 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Password',
                'edit' => 1,
                'field' => 'password',
                'id' => 4,
                'order' => 7,
                'read' => 0,
                'required' => 1,
                'type' => 'password',
            ),
            4 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Remember Token',
                'edit' => 0,
                'field' => 'remember_token',
                'id' => 5,
                'order' => 9,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            5 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 6,
                'order' => 10,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            6 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 7,
                'order' => 11,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            7 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Avatar',
                'edit' => 1,
                'field' => 'avatar',
                'id' => 8,
                'order' => 13,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            8 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":"0","taggable":"0"}',
                'display_name' => 'Role',
                'edit' => 1,
                'field' => 'user_belongsto_role_relationship',
                'id' => 9,
                'order' => 17,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            9 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'display_name' => 'Roles',
                'edit' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'id' => 10,
                'order' => 19,
                'read' => 0,
                'required' => 0,
                'type' => 'relationship',
            ),
            10 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Settings',
                'edit' => 0,
                'field' => 'settings',
                'id' => 11,
                'order' => 21,
                'read' => 0,
                'required' => 0,
                'type' => 'hidden',
            ),
            11 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 12,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            12 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 13,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            13 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 14,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            14 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 15,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            15 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 16,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            16 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 17,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            17 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 18,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            18 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 19,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            19 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Display Name',
                'edit' => 1,
                'field' => 'display_name',
                'id' => 20,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            20 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Role',
                'edit' => 1,
                'field' => 'role_id',
                'id' => 21,
                'order' => 14,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            21 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 22,
                'order' => 1,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            22 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":6}}',
                'display_name' => 'Codigo',
                'edit' => 1,
                'field' => 'codigo',
                'id' => 23,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            23 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":6}}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'nombre',
                'id' => 24,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            24 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 25,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            25 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 26,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            26 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 27,
                'order' => 6,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            27 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Nro',
                'edit' => 0,
                'field' => 'id',
                'id' => 68,
                'order' => 1,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            28 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Nit',
                'edit' => 1,
                'field' => 'nit',
                'id' => 69,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            29 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Razonsocial',
                'edit' => 1,
                'field' => 'razonsocial',
                'id' => 70,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            30 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Responsable',
                'edit' => 1,
                'field' => 'responsable',
                'id' => 71,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            31 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Dirección',
                'edit' => 1,
                'field' => 'direccion',
                'id' => 72,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            32 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Telefono',
                'edit' => 1,
                'field' => 'telefono',
                'id' => 73,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            33 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Fax',
                'edit' => 0,
                'field' => 'fax',
                'id' => 74,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            34 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Comentario',
                'edit' => 0,
                'field' => 'comentario',
                'id' => 75,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            35 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Condición',
                'edit' => 0,
                'field' => 'condicion',
                'id' => 76,
                'order' => 9,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            36 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 77,
                'order' => 10,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            37 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 78,
                'order' => 11,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            38 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 15,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Nro',
                'edit' => 0,
                'field' => 'id',
                'id' => 79,
                'order' => 1,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            39 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 15,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Branchoffice Id',
                'edit' => 1,
                'field' => 'branchoffice_id',
                'id' => 80,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            40 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 15,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'nombre',
                'id' => 81,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            41 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 15,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Condicion',
                'edit' => 0,
                'field' => 'condicion',
                'id' => 82,
                'order' => 4,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            42 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 15,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 83,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            43 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 15,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 84,
                'order' => 6,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            44 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 15,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 85,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            45 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 15,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\BranchOffice","table":"branch_offices","type":"belongsTo","column":"branchoffice_id","key":"id","label":"nombre","pivot_table":"administrative_directions","pivot":"0","taggable":"0"}',
                'display_name' => 'Sucursal',
                'edit' => 1,
                'field' => 'unit_belongsto_branch_office_relationship',
                'id' => 86,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            46 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 16,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 87,
                'order' => 1,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            47 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 16,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":6}}',
                'display_name' => 'Partida Id',
                'edit' => 1,
                'field' => 'partida_id',
                'id' => 88,
                'order' => 2,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            48 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 16,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":6}}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'nombre',
                'id' => 89,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            49 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 16,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":6}}',
                'display_name' => 'Presentacion',
                'edit' => 1,
                'field' => 'presentacion',
                'id' => 90,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            50 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 16,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Condicion',
                'edit' => 0,
                'field' => 'condicion',
                'id' => 91,
                'order' => 6,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            51 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 16,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 92,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            52 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 16,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 93,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            53 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 16,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 94,
                'order' => 9,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            54 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 16,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Partida","table":"partidas","type":"belongsTo","column":"partida_id","key":"id","label":"full_code","pivot_table":"archivos","pivot":"0","taggable":"0"}',
                'display_name' => 'Partida',
                'edit' => 1,
                'field' => 'article_belongsto_partida_relationship',
                'id' => 95,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            55 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 22,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Nro',
                'edit' => 0,
                'field' => 'id',
                'id' => 135,
                'order' => 1,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            56 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 22,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'nombre',
                'id' => 136,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            57 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 22,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Condicion',
                'edit' => 0,
                'field' => 'condicion',
                'id' => 137,
                'order' => 3,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            58 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 22,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 138,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            59 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 22,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 139,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            60 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 22,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 140,
                'order' => 6,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            61 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 23,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Nro',
                'edit' => 0,
                'field' => 'id',
                'id' => 141,
                'order' => 1,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            62 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 23,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'nombre',
                'id' => 142,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            63 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 23,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Ubicacion',
                'edit' => 1,
                'field' => 'ubicacion',
                'id' => 143,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            64 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 23,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Condicion',
                'edit' => 0,
                'field' => 'condicion',
                'id' => 144,
                'order' => 4,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            65 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 23,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 145,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            66 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 23,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 146,
                'order' => 6,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            67 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 23,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 147,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            68 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{"view":"almacenes.users.funcionario-browse"}',
                'display_name' => 'Funcionario',
                'edit' => 1,
                'field' => 'funcionario_id',
                'id' => 148,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            69 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Email Verified At',
                'edit' => 1,
                'field' => 'email_verified_at',
                'id' => 149,
                'order' => 12,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            70 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 25,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 157,
                'order' => 1,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            71 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 25,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'nombre',
                'id' => 158,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            72 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 25,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Descripcion',
                'edit' => 1,
                'field' => 'descripcion',
                'id' => 159,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            73 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 25,
                'delete' => 1,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'display_name' => 'Condicion',
                'edit' => 1,
                'field' => 'condicion',
                'id' => 160,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            74 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 25,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 161,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            75 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 25,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 162,
                'order' => 6,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            76 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 25,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 163,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            77 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 26,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 164,
                'order' => 1,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            78 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 26,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Categoria Id',
                'edit' => 1,
                'field' => 'categoria_id',
                'id' => 165,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            79 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 26,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'nombre',
                'id' => 166,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            80 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 26,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Presentacion',
                'edit' => 1,
                'field' => 'presentacion',
                'id' => 167,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            81 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 26,
                'delete' => 1,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'display_name' => 'Estado',
                'edit' => 1,
                'field' => 'condicion',
                'id' => 168,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            82 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 26,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 169,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            83 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 26,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 170,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            84 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 26,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 171,
                'order' => 9,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            85 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 26,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\DonacionCategoria","table":"donacion_categorias","type":"belongsTo","column":"categoria_id","key":"id","label":"nombre","pivot_table":"archivos","pivot":"0","taggable":"0"}',
                'display_name' => 'Categorias',
                'edit' => 1,
                'field' => 'donacion_articulo_belongsto_donacion_categoria_relationship_1',
                'id' => 173,
                'order' => 2,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            86 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 27,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Nro',
                'edit' => 0,
                'field' => 'id',
                'id' => 174,
                'order' => 1,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            87 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 27,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'nombre',
                'id' => 175,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            88 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 27,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Descripcion',
                'edit' => 1,
                'field' => 'descripcion',
                'id' => 176,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            89 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 27,
                'delete' => 1,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'display_name' => 'Estado',
                'edit' => 1,
                'field' => 'condicion',
                'id' => 177,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            90 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 27,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 178,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            91 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 27,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 179,
                'order' => 6,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            92 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 27,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 180,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            93 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 28,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Nro',
                'edit' => 0,
                'field' => 'id',
                'id' => 181,
                'order' => 1,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            94 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 28,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Centrocategoria Id',
                'edit' => 1,
                'field' => 'centrocategoria_id',
                'id' => 182,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            95 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 28,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'nombre',
                'id' => 183,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            96 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 28,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Direccion',
                'edit' => 1,
                'field' => 'direccion',
                'id' => 184,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            97 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 28,
                'delete' => 1,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'display_name' => 'Condicion',
                'edit' => 1,
                'field' => 'condicion',
                'id' => 185,
                'order' => 7,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            98 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 28,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 186,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            99 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 28,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 187,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            100 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 28,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 188,
                'order' => 9,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            101 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 28,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\CentroCategoria","table":"centro_categorias","type":"belongsTo","column":"centrocategoria_id","key":"id","label":"nombre","pivot_table":"archivos","pivot":"0","taggable":"0"}',
                'display_name' => 'Categoria',
                'edit' => 1,
                'field' => 'centro_belongsto_centro_categoria_relationship',
                'id' => 189,
                'order' => 2,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            102 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 29,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Nro',
                'edit' => 0,
                'field' => 'id',
                'id' => 190,
                'order' => 1,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            103 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 29,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Ci/Nit',
                'edit' => 1,
                'field' => 'ci',
                'id' => 191,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            104 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 29,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'nombre',
                'id' => 192,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            105 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 29,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Telefono',
                'edit' => 1,
                'field' => 'tel',
                'id' => 193,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            106 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 29,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Direccion',
                'edit' => 1,
                'field' => 'direccion',
                'id' => 194,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            107 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 29,
                'delete' => 1,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'display_name' => 'Estado',
                'edit' => 1,
                'field' => 'condicion',
                'id' => 195,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            108 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 29,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 196,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            109 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 29,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 197,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            110 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 29,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 198,
                'order' => 9,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            111 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 30,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Nro',
                'edit' => 0,
                'field' => 'id',
                'id' => 199,
                'order' => 1,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            112 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 30,
                'delete' => 1,
                'details' => '{"default":"0","options":{"0":"Empresa","1":"ONG"}}',
                'display_name' => 'Tipo',
                'edit' => 1,
                'field' => 'tipo',
                'id' => 200,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'radio_btn',
            ),
            113 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 30,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Nit',
                'edit' => 1,
                'field' => 'nit',
                'id' => 201,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            114 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 30,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Razon Social',
                'edit' => 1,
                'field' => 'razon',
                'id' => 202,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            115 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 30,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Telefono',
                'edit' => 1,
                'field' => 'tel',
                'id' => 203,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            116 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 30,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Direccion',
                'edit' => 1,
                'field' => 'direccion',
                'id' => 204,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            117 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 30,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Correo',
                'edit' => 1,
                'field' => 'correo',
                'id' => 205,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            118 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 30,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Responsable',
                'edit' => 1,
                'field' => 'responsable',
                'id' => 206,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            119 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 30,
                'delete' => 1,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'display_name' => 'Estado',
                'edit' => 1,
                'field' => 'condicion',
                'id' => 207,
                'order' => 9,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            120 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 30,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 208,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            121 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 30,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 209,
                'order' => 11,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            122 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 30,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 210,
                'order' => 12,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            123 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 28,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Sigla',
                'edit' => 1,
                'field' => 'sigla',
                'id' => 211,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            124 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 33,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 217,
                'order' => 1,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            125 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 33,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Key',
                'edit' => 1,
                'field' => 'key',
                'id' => 218,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            126 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 33,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Table Name',
                'edit' => 1,
                'field' => 'table_name',
                'id' => 219,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            127 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 33,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 220,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            128 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 33,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 221,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            129 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{"view":"almacenes.users.direccion-browse"}',
                'display_name' => 'Dirección / Unidad',
                'edit' => 0,
                'field' => 'direccionAdministrativa_id',
                'id' => 222,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'direccionadministrativa',
            ),
            130 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => '',
                'edit' => 0,
                'field' => 'sucursal_id',
                'id' => 223,
                'order' => 12,
                'read' => 0,
                'required' => 0,
                'type' => 'sucursal',
            ),
            131 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 16,
                'delete' => 0,
                'details' => '{}',
                'display_name' => '',
                'edit' => 0,
                'field' => 'sucursal_id',
                'id' => 224,
                'order' => 11,
                'read' => 0,
                'required' => 0,
                'type' => 'sucursal',
            ),
            132 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 14,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => 0,
                'field' => 'deleted_at',
                'id' => 225,
                'order' => 13,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            133 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 16,
                'delete' => 0,
                'details' => '{"display":{"width":12},"resize":{"width":"1000","height":null},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'display_name' => 'Imagen',
                'edit' => 1,
                'field' => 'image',
                'id' => 226,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            134 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Sucursal Id',
                'edit' => 1,
                'field' => 'sucursal_id',
                'id' => 227,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            135 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{"view":"almacenes.users.almacen-browse","model":"App\\\\Models\\\\Sucursal","table":"sucursals","type":"belongsTo","column":"sucursal_id","key":"id","label":"nombre","pivot_table":"archivos","pivot":"0","taggable":"0"}',
                'display_name' => 'Almacén / Sub Almacén',
                'edit' => 1,
                'field' => 'user_belongsto_sucursal_relationship',
                'id' => 228,
                'order' => 15,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            136 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Unidad',
                'edit' => 0,
                'field' => 'unidadAdministrativa_id',
                'id' => 229,
                'order' => 6,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            137 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{"model":"App\\\\Models\\\\SucursalSubAlmacen","table":"sucursal_sub_almacens","type":"belongsTo","column":"subSucursal_id","key":"id","label":"name","pivot_table":"archivos","pivot":"0","taggable":"0"}',
                'display_name' => 'Sub Almacen',
                'edit' => 1,
                'field' => 'user_belongsto_sucursal_sub_almacen_relationship',
                'id' => 230,
                'order' => 16,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            138 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{"view":"almacenes.users.contract-browse"}',
                'display_name' => 'Contrato',
                'edit' => 1,
                'field' => 'contract_id',
                'id' => 231,
                'order' => 18,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            139 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'SubSucursal Id',
                'edit' => 1,
                'field' => 'subSucursal_id',
                'id' => 232,
                'order' => 20,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
        ));
        
        
    }
}