<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-06-02 17:55:32',
                'icon_class' => 'voyager-home',
                'id' => 1,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.dashboard',
                'target' => '_self',
                'title' => 'Inicio',
                'updated_at' => '2022-10-21 15:31:25',
                'url' => '',
            ),
            1 => 
            array (
                'color' => NULL,
                'created_at' => '2021-06-02 17:55:32',
                'icon_class' => 'voyager-images',
                'id' => 2,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.media.index',
                'target' => '_self',
                'title' => 'Media',
                'updated_at' => '2021-06-02 14:07:22',
                'url' => '',
            ),
            2 => 
            array (
                'color' => NULL,
                'created_at' => '2021-06-02 17:55:32',
                'icon_class' => 'voyager-person',
                'id' => 3,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 11,
                'route' => 'voyager.users.index',
                'target' => '_self',
                'title' => 'Users',
                'updated_at' => '2021-06-02 14:08:02',
                'url' => '',
            ),
            3 => 
            array (
                'color' => NULL,
                'created_at' => '2021-06-02 17:55:32',
                'icon_class' => 'voyager-lock',
                'id' => 4,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 11,
                'route' => 'voyager.roles.index',
                'target' => '_self',
                'title' => 'Roles',
                'updated_at' => '2021-06-02 14:08:05',
                'url' => '',
            ),
            4 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-06-02 17:55:32',
                'icon_class' => 'voyager-tools',
                'id' => 5,
                'menu_id' => 1,
                'order' => 16,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Herramientas',
                'updated_at' => '2024-03-26 11:40:35',
                'url' => '',
            ),
            5 => 
            array (
                'color' => NULL,
                'created_at' => '2021-06-02 17:55:33',
                'icon_class' => 'voyager-list',
                'id' => 6,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.menus.index',
                'target' => '_self',
                'title' => 'Menu Builder',
                'updated_at' => '2021-06-02 14:07:22',
                'url' => '',
            ),
            6 => 
            array (
                'color' => NULL,
                'created_at' => '2021-06-02 17:55:33',
                'icon_class' => 'voyager-data',
                'id' => 7,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.database.index',
                'target' => '_self',
                'title' => 'Database',
                'updated_at' => '2021-06-02 14:07:22',
                'url' => '',
            ),
            7 => 
            array (
                'color' => NULL,
                'created_at' => '2021-06-02 17:55:33',
                'icon_class' => 'voyager-compass',
                'id' => 8,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.compass.index',
                'target' => '_self',
                'title' => 'Compass',
                'updated_at' => '2021-06-02 14:07:22',
                'url' => '',
            ),
            8 => 
            array (
                'color' => NULL,
                'created_at' => '2021-06-02 17:55:33',
                'icon_class' => 'voyager-bread',
                'id' => 9,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.bread.index',
                'target' => '_self',
                'title' => 'BREAD',
                'updated_at' => '2021-06-02 14:07:23',
                'url' => '',
            ),
            9 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-06-02 17:55:33',
                'icon_class' => 'voyager-settings',
                'id' => 10,
                'menu_id' => 1,
                'order' => 17,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.settings.index',
                'target' => '_self',
                'title' => 'Configuración',
                'updated_at' => '2024-03-26 11:40:35',
                'url' => '',
            ),
            10 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-06-02 14:07:53',
                'icon_class' => 'voyager-lock',
                'id' => 11,
                'menu_id' => 1,
                'order' => 15,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Seguridad',
                'updated_at' => '2024-03-26 11:40:35',
                'url' => '',
            ),
            11 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-06-25 18:03:59',
                'icon_class' => 'fa-solid fa-broom',
                'id' => 12,
                'menu_id' => 1,
                'order' => 18,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'clear.cache',
                'target' => '_self',
                'title' => 'Limpiar cache',
                'updated_at' => '2024-03-26 11:40:35',
                'url' => '',
            ),
            12 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-01-31 10:10:53',
                'icon_class' => 'voyager-hammer',
                'id' => 13,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => 'null',
                'parent_id' => 15,
                'route' => 'voyager.partidas.index',
                'target' => '_self',
                'title' => 'Partidas',
                'updated_at' => '2024-03-26 11:06:12',
                'url' => '',
            ),
            13 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-01-31 10:23:22',
                'icon_class' => 'voyager-list',
                'id' => 15,
                'menu_id' => 1,
                'order' => 11,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Opcion Almacen',
                'updated_at' => '2024-03-26 11:40:35',
                'url' => '',
            ),
            14 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-01-31 12:24:59',
                'icon_class' => 'fa-solid fa-shop',
                'id' => 21,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Ingresos y Egresos',
                'updated_at' => '2022-10-20 15:05:43',
                'url' => '',
            ),
            15 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-01-31 12:48:27',
                'icon_class' => 'voyager-milestone',
                'id' => 22,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => 'null',
                'parent_id' => 15,
                'route' => 'voyager.providers.index',
                'target' => '_self',
                'title' => 'Proveedores',
                'updated_at' => '2022-12-21 15:12:55',
                'url' => '',
            ),
            16 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-01-31 14:11:24',
                'icon_class' => 'voyager-plus',
                'id' => 24,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => 'null',
                'parent_id' => 21,
                'route' => 'income.index',
                'target' => '_self',
                'title' => 'Ingresos',
                'updated_at' => '2022-02-04 00:26:54',
                'url' => '',
            ),
            17 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-02-02 09:57:56',
                'icon_class' => 'voyager-move',
                'id' => 25,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 21,
                'route' => 'egres.index',
                'target' => '_self',
                'title' => 'Egresos',
                'updated_at' => '2022-02-02 09:58:19',
                'url' => '',
            ),
            18 => 
            array (
                'color' => NULL,
                'created_at' => '2022-02-03 16:13:34',
                'icon_class' => 'voyager-basket',
                'id' => 26,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => 15,
                'route' => 'voyager.articles.index',
                'target' => '_self',
                'title' => 'Artículos',
                'updated_at' => '2024-03-26 11:06:12',
                'url' => '',
            ),
            19 => 
            array (
                'color' => NULL,
                'created_at' => '2022-02-04 14:34:33',
                'icon_class' => 'voyager-file-text',
                'id' => 33,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => 15,
                'route' => 'voyager.modalities.index',
                'target' => '_self',
                'title' => 'Modalidades de Compras',
                'updated_at' => '2024-03-26 11:06:12',
                'url' => '',
            ),
            20 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-02-07 14:28:21',
                'icon_class' => 'fa-solid fa-shop',
                'id' => 34,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => 'null',
                'parent_id' => 15,
                'route' => 'voyager.sucursals.index',
                'target' => '_self',
                'title' => 'Sucursales',
                'updated_at' => '2022-12-21 15:12:55',
                'url' => '',
            ),
            21 => 
            array (
                'color' => NULL,
                'created_at' => '2022-02-15 21:07:50',
                'icon_class' => 'voyager-categories',
                'id' => 40,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => 42,
                'route' => 'voyager.donacion-categorias.index',
                'target' => '_self',
                'title' => 'Categorias',
                'updated_at' => '2022-02-20 18:13:36',
                'url' => '',
            ),
            22 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-02-15 21:14:50',
                'icon_class' => 'voyager-basket',
                'id' => 41,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => 'null',
                'parent_id' => 42,
                'route' => 'voyager.donacion-articulos.index',
                'target' => '_self',
                'title' => 'Articulos',
                'updated_at' => '2022-02-20 18:13:38',
                'url' => '',
            ),
            23 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-02-15 22:19:23',
                'icon_class' => 'voyager-double-down',
                'id' => 42,
                'menu_id' => 1,
                'order' => 14,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Parametros Donaciones',
                'updated_at' => '2024-03-26 11:40:35',
                'url' => '',
            ),
            24 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-02-15 22:23:09',
                'icon_class' => 'voyager-categories',
                'id' => 43,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => 'null',
                'parent_id' => 42,
                'route' => 'voyager.centro-categorias.index',
                'target' => '_self',
                'title' => 'Categorias',
                'updated_at' => '2022-02-15 22:23:56',
                'url' => '',
            ),
            25 => 
            array (
                'color' => NULL,
                'created_at' => '2022-02-15 22:49:51',
                'icon_class' => 'voyager-home',
                'id' => 44,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 42,
                'route' => 'voyager.centros.index',
                'target' => '_self',
                'title' => 'Centros de Establecimientos',
                'updated_at' => '2022-02-15 22:51:30',
                'url' => '',
            ),
            26 => 
            array (
                'color' => NULL,
                'created_at' => '2022-02-15 23:30:10',
                'icon_class' => 'voyager-person',
                'id' => 46,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 42,
                'route' => 'voyager.donador-personas.index',
                'target' => '_self',
                'title' => 'Personas',
                'updated_at' => '2022-02-20 18:12:23',
                'url' => '',
            ),
            27 => 
            array (
                'color' => NULL,
                'created_at' => '2022-02-15 23:54:51',
                'icon_class' => 'voyager-people',
                'id' => 47,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 42,
                'route' => 'voyager.donador-empresas.index',
                'target' => '_self',
                'title' => 'Empresas / ONG',
                'updated_at' => '2022-02-20 18:12:25',
                'url' => '',
            ),
            28 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-02-20 18:16:03',
                'icon_class' => 'voyager-receipt',
                'id' => 48,
                'menu_id' => 1,
                'order' => 12,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Ingresos Y Egresos',
                'updated_at' => '2024-03-26 11:40:35',
                'url' => '',
            ),
            29 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-02-20 18:16:54',
                'icon_class' => 'voyager-plus',
                'id' => 49,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 48,
                'route' => 'incomedonor.index',
                'target' => '_self',
                'title' => 'Ingreso',
                'updated_at' => '2022-02-20 18:19:31',
                'url' => '',
            ),
            30 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-02-20 18:18:43',
                'icon_class' => 'voyager-forward',
                'id' => 50,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 48,
                'route' => 'egressdonor.index',
                'target' => '_self',
                'title' => 'Egreso',
                'updated_at' => '2022-02-20 18:19:36',
                'url' => '',
            ),
            31 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-02-21 00:20:06',
                'icon_class' => 'voyager-basket',
                'id' => 51,
                'menu_id' => 1,
                'order' => 13,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'view_stock_donacion.index',
                'target' => '_self',
                'title' => 'Stock Consulta',
                'updated_at' => '2024-03-26 11:40:35',
                'url' => '',
            ),
            32 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-03-09 15:50:25',
                'icon_class' => 'voyager-basket',
                'id' => 52,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => 'null',
                'parent_id' => 48,
                'route' => 'donation.stock.view',
                'target' => '_self',
                'title' => 'Stock Disponible',
                'updated_at' => '2022-03-24 09:12:06',
                'url' => '',
            ),
            33 => 
            array (
                'color' => NULL,
                'created_at' => '2022-03-14 12:01:34',
                'icon_class' => 'voyager-key',
                'id' => 54,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 11,
                'route' => 'voyager.permissions.index',
                'target' => '_self',
                'title' => 'Permissions',
                'updated_at' => '2022-03-14 12:02:01',
                'url' => '',
            ),
            34 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-09-26 14:09:43',
                'icon_class' => 'fa-solid fa-print',
                'id' => 55,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => 'null',
                'parent_id' => 60,
                'route' => 'almacen-inventarioAnual-partida.report',
                'target' => '_self',
                'title' => 'Inv. Anual Por Partida',
                'updated_at' => '2024-01-10 09:43:34',
                'url' => '',
            ),
            35 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-09-26 15:33:20',
                'icon_class' => 'fa-solid fa-print',
                'id' => 57,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => 'null',
                'parent_id' => 60,
                'route' => 'almacen-inventarioAnual-da.report',
                'target' => '_self',
                'title' => 'Inv. Anual Por DA',
                'updated_at' => '2022-10-19 11:38:41',
                'url' => '',
            ),
            36 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-10-10 09:29:01',
                'icon_class' => 'fa-solid fa-print',
                'id' => 58,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => 'null',
                'parent_id' => 60,
                'route' => 'almacen-inventarioAnual-detalle.report',
                'target' => '_self',
                'title' => 'Inv. Anual Detalle "Item"',
                'updated_at' => '2024-01-10 09:43:34',
                'url' => '',
            ),
            37 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-10-11 09:14:17',
                'icon_class' => 'fa-solid fa-print',
                'id' => 59,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => 'null',
                'parent_id' => 61,
                'route' => 'almacen-article-stock.report',
                'target' => '_self',
                'title' => 'Stock disponible',
                'updated_at' => '2024-03-26 11:06:20',
                'url' => '',
            ),
            38 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-10-19 11:08:22',
                'icon_class' => 'fa-solid fa-chart-pie',
                'id' => 60,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Reporte Anuales',
                'updated_at' => '2024-03-26 11:40:35',
                'url' => '',
            ),
            39 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-10-19 11:08:55',
                'icon_class' => 'fa-solid fa-chart-pie',
                'id' => 61,
                'menu_id' => 1,
                'order' => 8,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Reporte Artículos',
                'updated_at' => '2024-03-26 11:40:35',
                'url' => '',
            ),
            40 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-10-19 11:18:26',
                'icon_class' => 'fa-solid fa-chart-pie',
                'id' => 62,
                'menu_id' => 1,
                'order' => 10,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Reporte Proveedores',
                'updated_at' => '2024-03-26 11:40:35',
                'url' => '',
            ),
            41 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-10-19 11:40:38',
                'icon_class' => 'fa-solid fa-print',
                'id' => 63,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 61,
                'route' => 'almacen-article-list.report',
                'target' => '_self',
                'title' => 'Lista de Artículos',
                'updated_at' => '2022-10-19 14:16:58',
                'url' => '',
            ),
            42 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-10-19 11:42:05',
                'icon_class' => 'fa-solid fa-print',
                'id' => 64,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 62,
                'route' => 'almacen-provider-list.report',
                'target' => '_self',
                'title' => 'Lista de Proveedores',
                'updated_at' => '2022-10-19 11:42:24',
                'url' => '',
            ),
            43 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-10-19 14:16:15',
                'icon_class' => 'fa-solid fa-print',
                'id' => 65,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => 'null',
                'parent_id' => 61,
                'route' => 'almacen-article-incomeOffice.report',
                'target' => '_self',
                'title' => 'Ingresos por Oficinas',
                'updated_at' => '2024-03-26 11:06:20',
                'url' => '',
            ),
            44 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-10-19 14:16:37',
                'icon_class' => 'fa-solid fa-print',
                'id' => 66,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => 61,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Ingresos por DA',
                'updated_at' => '2024-03-26 11:06:20',
                'url' => '',
            ),
            45 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-10-21 09:06:27',
                'icon_class' => 'fa-solid fa-print',
                'id' => 67,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 61,
                'route' => 'almacen-article-egressOffice.report',
                'target' => '_self',
                'title' => 'Egresos Por Oficinas',
                'updated_at' => '2024-03-26 11:06:20',
                'url' => '',
            ),
            46 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-12-15 12:53:24',
                'icon_class' => 'fa-solid fa-print',
                'id' => 68,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => 'null',
                'parent_id' => 62,
                'route' => 'almacen-user-list.report',
                'target' => '_self',
                'title' => 'Usuarios',
                'updated_at' => '2022-12-15 12:54:14',
                'url' => '',
            ),
            47 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-12-21 15:12:10',
                'icon_class' => 'fa-solid fa-person-digging',
                'id' => 70,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => 'null',
                'parent_id' => 15,
                'route' => 'people_ext.index',
                'target' => '_self',
                'title' => 'Personas Externas',
                'updated_at' => '2022-12-21 15:13:00',
                'url' => '',
            ),
            48 => 
            array (
                'color' => '#000000',
                'created_at' => '2023-01-21 22:00:39',
                'icon_class' => 'fa-solid fa-chart-pie',
                'id' => 71,
                'menu_id' => 1,
                'order' => 9,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Reporte Partida',
                'updated_at' => '2024-03-26 11:40:35',
                'url' => '',
            ),
            49 => 
            array (
                'color' => '#000000',
                'created_at' => '2023-01-21 22:05:56',
                'icon_class' => 'fa-solid fa-print',
                'id' => 72,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => 'null',
                'parent_id' => 71,
                'route' => 'almacen-partida-incomearticle.report',
                'target' => '_self',
                'title' => 'Ingresos Artículo Gestión',
                'updated_at' => '2023-01-21 22:06:47',
                'url' => '',
            ),
            50 => 
            array (
                'color' => '#000000',
                'created_at' => '2023-04-06 09:36:22',
                'icon_class' => 'fa-solid fa-cart-shopping',
                'id' => 73,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'outbox.index',
                'target' => '_self',
                'title' => 'Pedidos',
                'updated_at' => '2024-03-26 11:40:35',
                'url' => '',
            ),
            51 => 
            array (
                'color' => '#000000',
                'created_at' => '2023-04-06 09:39:57',
                'icon_class' => 'fa-regular fa-clipboard',
                'id' => 74,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'inbox.index',
                'target' => '_self',
                'title' => 'Solicitudes',
                'updated_at' => '2024-03-26 11:40:35',
                'url' => '',
            ),
            52 => 
            array (
                'color' => '#000000',
                'created_at' => '2023-07-02 17:08:16',
                'icon_class' => 'fa-solid fa-store',
                'id' => 75,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'existingproducts.index',
                'target' => '_self',
                'title' => 'Producto en Existencia',
                'updated_at' => '2024-03-26 11:40:35',
                'url' => '',
            ),
            53 => 
            array (
                'color' => '#000000',
                'created_at' => '2024-01-10 09:42:59',
                'icon_class' => 'fa-solid fa-print',
                'id' => 76,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => 'null',
                'parent_id' => 60,
                'route' => 'almacen-inventarioAnual-da-central.report',
                'target' => '_self',
                'title' => 'Inv . Anual DA Central',
                'updated_at' => '2024-01-10 09:43:34',
                'url' => '',
            ),
            54 => 
            array (
                'color' => '#000000',
                'created_at' => '2024-03-26 11:00:37',
                'icon_class' => 'fa fa-clipboard',
                'id' => 77,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'nonstock.inbox',
                'target' => '_self',
                'title' => 'Solic. Inexistencia',
                'updated_at' => '2024-03-26 11:59:16',
                'url' => '',
            ),
        ));
        
        
    }
}